/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_tcf_impl_TCAPIConnection */

#ifndef _Included_com_nokia_tcf_impl_TCAPIConnection
#define _Included_com_nokia_tcf_impl_TCAPIConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeConnect
 * Signature: (Ljava/lang/String;[J[Ljava/lang/String;[JLjava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeConnect
  (JNIEnv *, jobject, jstring, jlongArray, jobjectArray, jlongArray, jstring, jlongArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeDisconnect
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeDisconnect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeGetNumberConnections
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeGetNumberConnections
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeGetTypeOfConnection
 * Signature: (J[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeGetTypeOfConnection
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeGetConnectionSettings
 * Signature: (J[Ljava/lang/String;[J[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeGetConnectionSettings
  (JNIEnv *, jobject, jlong, jobjectArray, jlongArray, jobjectArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativePollError
 * Signature: (J[I[Z[J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativePollError
  (JNIEnv *, jobject, jlong, jintArray, jbooleanArray, jlongArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeGetNumberVersionEntities
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeGetNumberVersionEntities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeGetVersion
 * Signature: (JJ[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeGetVersion
  (JNIEnv *, jobject, jlong, jlong, jobjectArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativePollInputStream
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativePollInputStream
  (JNIEnv *, jobject, jlong, jlongArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativePollInputStream2
 * Signature: (JJ[J[J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativePollInputStream2
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jlongArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeGetInputStreamMessageBytes
 * Signature: (JJ[J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeGetInputStreamMessageBytes
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeReadInputStream
 * Signature: (JJ[J[JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeReadInputStream
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jlongArray, jlong, jbyteArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeOpenInputStream
 * Signature: (JLjava/lang/String;JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeOpenInputStream
  (JNIEnv *, jobject, jlong, jstring, jlong, jboolean);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeCloseInputStream
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeCloseInputStream
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeClearFile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeClearFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeSendMessage
 * Signature: (J[J[Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeSendMessage
  (JNIEnv *, jobject, jlong, jlongArray, jobjectArray, jbyteArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeSetMessageIds
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeSetMessageIds
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeStart
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeStop
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeTestConnection
 * Signature: (Ljava/lang/String;[J[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeTestConnection__Ljava_lang_String_2_3J_3Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jlongArray, jobjectArray);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeTestConnection
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeTestConnection__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeStartServer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeStartServer
  (JNIEnv *, jobject);

/*
 * Class:     com_nokia_tcf_impl_TCAPIConnection
 * Method:    nativeStopServer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_nokia_tcf_impl_TCAPIConnection_nativeStopServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
