/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.sdt.emf.component;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping Instance Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * 
 * 		Base for mapping resources generated by component instances.
 * 		Either a reference to the resource is emitted (for LLINK targets)
 * 		or the resource expression is emitted (for STRUCT targets).
 * 		
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link com.nokia.sdt.emf.component.MappingInstanceType#getRsrcId <em>Rsrc Id</em>}</li>
 * </ul>
 * </p>
 *
 * @see com.nokia.sdt.emf.component.ComponentPackage#getMappingInstanceType()
 * @model extendedMetaData="name='mappingInstanceType' kind='empty'"
 * @generated
 */
public interface MappingInstanceType extends TwoWayMappingType{
	/**
	 * Returns the value of the '<em><b>Rsrc Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
     * <p>
     * If the meaning of the '<em>Rsrc Id</em>' attribute isn't clear,
     * there really should be more of a description here...
     * </p>
     * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * 
	 * 					If specified, which particular resource to match.
	 * 					
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Rsrc Id</em>' attribute.
	 * @see #setRsrcId(String)
	 * @see com.nokia.sdt.emf.component.ComponentPackage#getMappingInstanceType_RsrcId()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.String"
	 *        extendedMetaData="kind='attribute' name='rsrcId'"
	 * @generated
	 */
    String getRsrcId();

	/**
	 * Sets the value of the '{@link com.nokia.sdt.emf.component.MappingInstanceType#getRsrcId <em>Rsrc Id</em>}' attribute.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Rsrc Id</em>' attribute.
	 * @see #getRsrcId()
	 * @generated
	 */
    void setRsrcId(String value);

} // MappingInstanceType
