/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.nokia.sdt.emf.component;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping Reference Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <!-- begin-model-doc -->
 * 
 * 		Base for mapping references to resources generated by component instances.
 * 		
 * <!-- end-model-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link com.nokia.sdt.emf.component.MappingReferenceType#getRsrcId <em>Rsrc Id</em>}</li>
 * </ul>
 * </p>
 *
 * @see com.nokia.sdt.emf.component.ComponentPackage#getMappingReferenceType()
 * @model extendedMetaData="name='mappingReferenceType' kind='empty'"
 * @generated
 */
public interface MappingReferenceType extends TwoWayMappingType{
	/**
	 * Returns the value of the '<em><b>Rsrc Id</b></em>' attribute.
	 * <!-- begin-user-doc -->
     * <p>
     * If the meaning of the '<em>Rsrc Id</em>' attribute isn't clear,
     * there really should be more of a description here...
     * </p>
     * <!-- end-user-doc -->
	 * <!-- begin-model-doc -->
	 * 
	 * 					If defined, tells which particular generated resource to reference.
	 * 					
	 * <!-- end-model-doc -->
	 * @return the value of the '<em>Rsrc Id</em>' attribute.
	 * @see #setRsrcId(String)
	 * @see com.nokia.sdt.emf.component.ComponentPackage#getMappingReferenceType_RsrcId()
	 * @model unique="false" dataType="org.eclipse.emf.ecore.xml.type.String"
	 *        extendedMetaData="kind='attribute' name='rsrcId'"
	 * @generated
	 */
    String getRsrcId();

	/**
	 * Sets the value of the '{@link com.nokia.sdt.emf.component.MappingReferenceType#getRsrcId <em>Rsrc Id</em>}' attribute.
	 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Rsrc Id</em>' attribute.
	 * @see #getRsrcId()
	 * @generated
	 */
    void setRsrcId(String value);

} // MappingReferenceType
