/*
* Copyright (c) 2005 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/

package com.nokia.sdt.sourcegen.templates.backend;

/**
 * Visitor for the chunks generated by the BackEnd.
 * 
 */
public interface ITextChunkVisitor {
    public void visit(ExprTextChunk chunk);
    public void visit(RawTextChunk chunk, boolean isFirst, boolean isLast);
    public void visit(ScriptTextChunk chunk);
    public void visit(LiteralTextChunk chunk);
}
