<integer key="informationMessage.padding" value="2"/> <!-- internal border -->
<integer key="informationMessage.lineGap" value="0"/>
<integer key="informationMessage.text.top.margin" value="9"/>
<integer key="informationMessage.text.bottom.margin" value="11"/>
<integer key="informationMessage.text.left.margin" value="10"/>
<integer key="informationMessage.text.right.margin" value="5"/>

<integer key="informationMessage.alignment.EHLeftVTop.leftMargin" value="13"/>
<integer key="informationMessage.alignment.EHLeftVTop.rightMargin" value="15"/>
<integer key="informationMessage.alignment.EHLeftVTop.topMargin" value="11"/>
<integer key="informationMessage.alignment.EHLeftVTop.bottomMargin" value="153"/>

<integer key="informationMessage.alignment.EHLeftVCenter.leftMargin" value="13"/>
<integer key="informationMessage.alignment.EHLeftVCenter.rightMargin" value="15"/>
<integer key="informationMessage.alignment.EHLeftVCenter.topMargin" value="55"/>
<integer key="informationMessage.alignment.EHLeftVCenter.bottomMargin" value="109"/>

<integer key="informationMessage.alignment.EHLeftVBottom.leftMargin" value="13"/>
<integer key="informationMessage.alignment.EHLeftVBottom.rightMargin" value="15"/>
<integer key="informationMessage.alignment.EHLeftVBottom.topMargin" value="100"/>
<integer key="informationMessage.alignment.EHLeftVBottom.bottomMargin" value="64"/>

<integer key="informationMessage.alignment.EHCenterVTop.leftMargin" value="14"/>
<integer key="informationMessage.alignment.EHCenterVTop.rightMargin" value="14"/>
<integer key="informationMessage.alignment.EHCenterVTop.topMargin" value="11"/>
<integer key="informationMessage.alignment.EHCenterVTop.bottomMargin" value="153"/>

<integer key="informationMessage.alignment.EHCenterVCenter.leftMargin" value="14"/>
<integer key="informationMessage.alignment.EHCenterVCenter.rightMargin" value="14"/>
<integer key="informationMessage.alignment.EHCenterVCenter.topMargin" value="55"/>
<integer key="informationMessage.alignment.EHCenterVCenter.bottomMargin" value="109"/>

<integer key="informationMessage.alignment.EHCenterVBottom.leftMargin" value="14"/>
<integer key="informationMessage.alignment.EHCenterVBottom.rightMargin" value="14"/>
<integer key="informationMessage.alignment.EHCenterVBottom.topMargin" value="100"/>
<integer key="informationMessage.alignment.EHCenterVBottom.bottomMargin" value="64"/>

<integer key="informationMessage.alignment.EHRightVTop.leftMargin" value="15"/>
<integer key="informationMessage.alignment.EHRightVTop.rightMargin" value="13"/>
<integer key="informationMessage.alignment.EHRightVTop.topMargin" value="11"/>
<integer key="informationMessage.alignment.EHRightVTop.bottomMargin" value="153"/>

<integer key="informationMessage.alignment.EHRightVCenter.leftMargin" value="15"/>
<integer key="informationMessage.alignment.EHRightVCenter.rightMargin" value="13"/>
<integer key="informationMessage.alignment.EHRightVCenter.topMargin" value="55"/>
<integer key="informationMessage.alignment.EHRightVCenter.bottomMargin" value="109"/>

<integer key="informationMessage.alignment.EHRightVBottom.leftMargin" value="15"/>
<integer key="informationMessage.alignment.EHRightVBottom.rightMargin" value="13"/>
<integer key="informationMessage.alignment.EHRightVBottom.topMargin" value="100"/>
<integer key="informationMessage.alignment.EHRightVBottom.bottomMargin" value="64"/>