<!-- font entries are searched relative to the data/fonts directory -->

<font key="ArialNarrowFont.portrait" initData="/data/fonts/ARIALN.ttf" size="12" />
<font key="NormalFont.portrait" initData="/data/fonts/s60ssb.ttf" size="10" />
<font key="NormalFont.portrait" initData="/data/fonts/s60ssb.ttf" size="11" />
<font key="AnnotationFont.portrait" initData="/data/fonts/s60ssb.ttf" size="9" />
<font key="LegendFont.portrait" initData="/data/fonts/s60ssb.ttf" size="10" />

<font key="ArialNarrowFont.landscape" initData="/data/fonts/ARIALN.ttf" size="12" />
<font key="NormalFont.landscape" initData="/data/fonts/s60ssb.ttf" size="10" />
<font key="AnnotationFont.landscape" initData="/data/fonts/s60ssb.ttf" size="9" />
<font key="LegendFont.landscape" initData="/data/fonts/s60ssb.ttf" size="10" />