<!-- these definitions are common to every laf -->

<color key="screen.background" r="255" g="255" b="255"/>

<color key="EEikColorWindowBackground" r="255" g="255" b="255"/>
<color key="EEikColorWindowText" r="0" g="0" b="0"/>
<color key="EEikColorControlBackground" r="255" g="255" b="255"/>
<color key="EEikColorControlText" r="0" g="0" b="0"/>
<color key="EEikColorControlSurroundBackground" r="100" g="100" b="100"/>
<color key="EEikColorControlSurroundText" r="0" g="0" b="0"/>
<color key="EEikColorControlHighlightBackground" r="200" g="200" b="200"/>
<color key="EEikColorControlHighlightText" r="0" g="0" b="0"/>
<color key="EEikColorControlDimmedBackground" r="200" g="200" b="200"/>
<color key="EEikColorControlDimmedText" r="100" g="100" b="100"/>
<color key="EEikColorControlDimmedHighlightBackground" r="200" g="200" b="200"/>
<color key="EEikColorControlDimmedHighlightText" r="100" g="100" b="100"/>
<color key="EEikColorDialogBackground" r="255" g="255" b="255"/>
<color key="EEikColorDialogText" r="0" g="0" b="0"/>
<color key="EEikColorDialogTitle" r="200" g="200" b="200"/>
<color key="EEikColorDialogTitlePressed" r="200" g="200" b="200"/>
<color key="EEikColorDialogTitleText" r="0" g="0" b="0"/>
<color key="EEikColorDialogTitleTextPressed" r="0" g="0" b="0"/>
<color key="EEikColorMenubarBackground" r="255" g="255" b="255"/>
<color key="EEikColorMenubarText" r="0" g="0" b="0"/>
<color key="EEikColorMenubarTitleBackground" r="255" g="255" b="255"/>
<color key="EEikColorMenubarTitleText" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneBackground" r="255" g="255" b="255"/>
<color key="EEikColorMenuPaneText" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneHighlight" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneTextHighlight" r="255" g="255" b="255"/>
<color key="EEikColorMenuPaneDimmedHighlight" r="255" g="255" b="255"/>
<color key="EEikColorMenuPaneDimmedText" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneDimmedTextHighlight" r="0" g="0" b="0"/>
<color key="EEikColorButtonFaceClear" r="255" g="255" b="255"/>
<color key="EEikColorButtonFaceSet" r="255" g="255" b="255"/>
<color key="EEikColorButtonFaceSetPressed" r="255" g="255" b="255"/>
<color key="EEikColorButtonFaceClearPressed" r="255" g="255" b="255"/>
<color key="EEikColorButtonText" r="0" g="0" b="0"/>
<color key="EEikColorButtonTextPressed" r="0" g="0" b="0"/>
<color key="EEikColorButtonTextDimmed" r="0" g="0" b="0"/>
<color key="EEikColorMsgWinForeground" r="0" g="0" b="0"/>
<color key="EEikColorMsgWinBackground" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarBorder" r="100" g="100" b="100"/>
<color key="EEikColorScrollBarShaft" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarShaftDimmed" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarShaftPressed" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarNoShaftOrThumb" r="255" g="255" b="25"/>
<color key="EEikColorScrollButtonIcon" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonIconPressed" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonIconDimmed" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonThumbBackground" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonThumbBackgroundPressed" r="255" g="255" b="255"/>
<color key="EEikColorScrollThumbDimmed" r="255" g="255" b="25"/>
<color key="EEikColorScrollThumbEdge" r="255" g="255" b="255"/>
<color key="EEikColorToolbarBackground" r="255" g="255" b="255"/>
<color key="EEikColorToolbarText" r="0" g="0" b="0"/>
<color key="EEikColorStatusPaneText" r="0" g="0" b="0"/>
<color key="EEikColorLabelText" r="0" g="0" b="0"/>
<color key="EEikColorLabelTextEmphasis" r="0" g="0" b="0"/>
<color key="EEikColorLabelDimmedText" r="0" g="0" b="0"/>
<color key="EEikColorLabelHighlightPartialEmphasis" r="255" g="255" b="255"/>
<color key="EEikColorLabelHighlightFullEmphasis" r="255" g="255" b="255"/>
<color key="EEikColorProgressBar" r="252" g="215" b="129"/>
<color key="EEikColorProgressBarDimmed" r="131" g="176" b="203"/>

<color key="EEikColorLabelBackgroundPartialEmphasis" r="85" g="85" b="85"/>
<color key="EEikColorLabelBackgroundFullEmphasis" r="0" g="0" b="0"/>

<colorAlias key="EEikColorStatusPaneBackground" ref="screen.background"/>

<image key="commandButton.noSet.background" imageFile="button.noSet.background.png"/>
<image key="commandButton.set.background" imageFile="button.set.background.png"/>

<image key="bitmapButton.noSet.background" imageFile="button.noSet.background.png"/>
<image key="bitmapButton.set.background" imageFile="button.set.background.png"/>

<image key="textButton.noSet.background" imageFile="button.noSet.background.png"/>
<image key="textButton.set.background" imageFile="button.set.background.png"/>