<!-- values for LAF keys that differ between portrait and landscape styles: landscape settings -->

<boolean key="is.portrait" value="false"/>
<boolean key="is.landscape" value="true"/>

<!-- define fonts, colors, rectangles, integers below... -->

<fontAlias key="ArialNarrowFont" ref="ArialNarrowFont.landscape" />
<fontAlias key="NormalFont" ref="NormalFont.landscape" />
<fontAlias key="AnnotationFont" ref="AnnotationFont.landscape" />
<fontAlias key="LegendFont" ref="LegendFont.landscape" />
