<!-- values for LAF keys that differ between portrait and landscape styles: portrait settings -->

<boolean key="is.portrait" value="true"/>
<boolean key="is.landscape" value="false"/>

<!-- define fonts, colors, rectangles, integers below... -->

<fontAlias key="ArialNarrowFont" ref="ArialNarrowFont.portrait" />
<fontAlias key="NormalFont" ref="NormalFont.portrait" />
<fontAlias key="AnnotationFont" ref="AnnotationFont.portrait" />
<fontAlias key="LegendFont" ref="LegendFont.portrait" />