/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage */

#ifndef _Included_com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage
#define _Included_com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_NOT_CHECKED
#define com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_NOT_CHECKED 0L
#undef com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_TRK_SERVER_ERROR
#define com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_TRK_SERVER_ERROR 1L
#undef com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_SERIAL_PORT_ERROR
#define com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_SERIAL_PORT_ERROR 2L
#undef com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_CONNECT_TRK_ERROR
#define com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_CONNECT_TRK_ERROR 3L
#undef com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_INSTALLED_TRK_OK_STATUS
#define com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_INSTALLED_TRK_OK_STATUS 4L
#undef com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_NEWER_TRK_AVAILABLE_STATUS
#define com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_NEWER_TRK_AVAILABLE_STATUS 5L
/*
 * Class:     com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage
 * Method:    getTRKVersion
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_nokia_carbide_trk_support_onDeviceSetup_ui_CheckExistingTRKPage_getTRKVersion
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
