/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nokia_carbide_trk_support_service_TRKConnectedService */

#ifndef _Included_com_nokia_carbide_trk_support_service_TRKConnectedService
#define _Included_com_nokia_carbide_trk_support_service_TRKConnectedService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nokia_carbide_trk_support_service_TRKConnectedService
 * Method:    getTRKVersionFromSerial
 * Signature: (Ljava/lang/String;IIIII[I)V
 */
JNIEXPORT void JNICALL Java_com_nokia_carbide_trk_support_service_TRKConnectedService_getTRKVersionFromSerial
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
