<event name="handleStatusPaneSizeChange" category="View" 
    handlerNameTemplate="Handle{title(name)}StatusPaneSizeChange"
    descriptionKey="handleStatusPaneSizeChangeDescription"
/>
<event name="handleCommand" category="View" 
    handlerNameTemplate="Handle{title(name)}CommandL"
    descriptionKey="handleCommandDescription"
/>
<event name="activated" category="View" 
    handlerNameTemplate="Handle{title(name)}ActivatedL"
    descriptionKey="activatedDescription"
/>
<event name="deactivated" category="View" 
    handlerNameTemplate="Handle{title(name)}Deactivated"
    descriptionKey="deactivatedDescription"
/>
