<!--START_USECASES: CU19 END_USECASES-->

		<!-- This maps the common fields of either CEIKEDWIN, GTXTED or RTXTED resources -->
		
				<mapBitmaskMember property="flags" member="flags">
					<mapBitmaskValue properties="EEikEdwinAllowPictures" value="EEikEdwinAllowPictures"/>
					<mapBitmaskValue properties="EEikEdwinAllowUndo" value="EEikEdwinAllowUndo"/>
					<mapBitmaskValue properties="EEikEdwinAlwaysShowSelection" value="EEikEdwinAlwaysShowSelection"/>
					<mapBitmaskValue properties="EEikEdwinCustomWrap" value="EEikEdwinCustomWrap"/> 
					<mapBitmaskValue properties="EEikEdwinDisableAutoCurEnd" value="EEikEdwinDisableAutoCurEnd"/>
					<mapBitmaskValue properties="EEikEdwinDisplayOnly" value="EEikEdwinDisplayOnly"/>
					<mapBitmaskValue properties="EEikEdwinEnableAutoSelection" value="EEikEdwinEnableAutoSelection"/>
					<mapBitmaskValue properties="EEikEdwinFindStringMaxLen" value="EEikEdwinFindStringMaxLen"/>
					<mapBitmaskValue properties="EEikEdwinIgnoreVirtualCursor" value="EEikEdwinIgnoreVirtualCursor"/>
					<mapBitmaskValue properties="EEikEdwinInclusiveSizeFixed" value="EEikEdwinInclusiveSizeFixed"/>
					<mapBitmaskValue properties="EEikEdwinJustAutoCurEnd" value="EEikEdwinJustAutoCurEnd"/>
					<mapBitmaskValue properties="EEikEdwinKeepDocument" value="EEikEdwinKeepDocument"/>
					<mapBitmaskValue properties="EEikEdwinLineCursor" value="EEikEdwinLineCursor"/>
					<mapBitmaskValue properties="EEikEdwinNoAutoSelection" value="EEikEdwinNoAutoSelection"/>
					<mapBitmaskValue properties="EEikEdwinNoCursorWrap" value="EEikEdwinNoCursorWrap"/>
					<mapBitmaskValue properties="EEikEdwinNoCursorWrapUp" value="EEikEdwinNoCursorWrapUp"/>
					<mapBitmaskValue properties="EEikEdwinNoCustomDraw" value="EEikEdwinNoCustomDraw"/>
					<mapBitmaskValue properties="EEikEdwinNoHorizScrolling" value="EEikEdwinNoHorizScrolling"/>
					<mapBitmaskValue properties="EEikEdwinNoLineOrParaBreaks" value="EEikEdwinNoLineOrParaBreaks"/>
					<mapBitmaskValue properties="EEikEdwinNoTextParsers" value="EEikEdwinNoTextParsers"/>
					<mapBitmaskValue properties="EEikEdwinNoWrap" value="EEikEdwinNoWrap"/>
					<mapBitmaskValue properties="EEikEdwinOnlyASCIIChars" value="EEikEdwinOnlyASCIIChars"/>
					<mapBitmaskValue properties="EEikEdwinOwnsWindow" value="EEikEdwinOwnsWindow"/>
					<mapBitmaskValue properties="EEikEdwinReadOnly" value="EEikEdwinReadOnly"/>
					<mapBitmaskValue properties="EEikEdwinResizable" value="EEikEdwinResizable"/>
					<mapBitmaskValue properties="EEikEdwinSegmentedStorage" value="EEikEdwinSegmentedStorage"/>
					<mapBitmaskValue properties="EEikEdwinUserSuppliedText" value="EEikEdwinUserSuppliedText"/>
					<mapBitmaskValue properties="EEikEdwinWidthInPixels" value="EEikEdwinWidthInPixels"/>					
				</mapBitmaskMember>	