<!--START_USECASES: CU17 END_USECASES-->

		<!-- This maps the common fields of either BMPBUT, CMBUT or TXTBUT resources -->
		
				<mapBitmaskMember property="behavior" member="behavior">
					<mapBitmaskValue properties="EEikButStaysClear" value="EEikButStaysClear"/>
					<mapBitmaskValue properties="EEikButStaysSet" value="EEikButStaysSet"/>
					<mapBitmaskValue properties="EEikButLatches" value="EEikButLatches"/>
					<mapBitmaskValue properties="EEikButReportOnPointerDown" value="EEikButReportOnPointerDown"/> 					
				</mapBitmaskMember>	