		<implementation>
			<interface id="com.nokia.sdt.datamodel.adapter.IVisualAppearance"/>
			<interface id="com.nokia.sdt.datamodel.adapter.IDirectLabelEdit"/>
			<script file="CBA_visual.js" prototype="CBAVisual"/>
		</implementation>
		<implementation>
			<interface id="com.nokia.sdt.datamodel.adapter.IReconcileProperty"/>
			<script file="CBA_reconcile.js" prototype="CBAReconcile"/>
		</implementation>