<dimension key="navi.indicator.size" width="8" height="15"/>

<dimension key="context.icon.size" width="44" height="44"/>

<dimension key="note.icon.size" width="30" height="40" />
<dimension key="note.inset" width="2" height="0" />
<integer key="note.padding" value="2" />
<rectangle key="query.editor" x="9" y="5" width="150" height="23" />

<integer key="form.inset" value="20"/>
<integer key="form.divider.offset.single" value="50"/>
<integer key="form.divider.offset.double" value="6"/>
<integer key="form.padding" value="5"/>
<dimension key="form.image.size" width="16" height="16"/>

<integer key="list.padding" value="6"/>
<maskedImage key="listbox.mark.icon" imageFile="qgn_indi_marked_add.bmp" maskFile="qgn_indi_marked_add_mask.bmp"/>

<integer key="settingitemlist.numbered.padding" value="20"/>
<integer key="settingitemlist.padding.y" value="3"/>
<integer key="settingitemlist.padding.x" value="6"/>
<integer key="settingitemlist.content.x" value="40"/>
<integer key="settingitemlist.indi.padding" value="4"/>
<integer key="settingitemlist.content.height" value="16"/>


<integer key="naviVolume.bar.width" value="5"/>
<integer key="naviVolume.bar.arcWidth" value="5"/>
<integer key="naviVolume.bar.arcHeight" value="5"/>


<integer key="volume.bar.width" value="6"/>
<integer key="volume.padding.height" value="4"/>

<integer key="progress.bar.height" value="10"/>
<integer key="note.progress.offsetFromBottom" value="20"/>

<integer key="tab.corner" value="2"/>

<integer key="list.row.height.single" value="22" />
<integer key="list.row.height.double" value="44" />
<integer key="list.row.height.single.large" value="44" />
<integer key="list.query.row.height.single" value="22" />
<integer key="list.query.row.height.double" value="44" />
<integer key="list.query.row.height.single.large" value="44" />

<integer key="note.text.lineGap" value="3" />

<!-- These dimensions are used in every layout. 

	The pattern is, x and y are absolute.
	If width is negative, the right side is calculated as the RHS of the parent
	plus this negative width.  Same goes for height.  
	Otherwise (non-negative), the width and height are absolute.
-->

<rectangle key="listitem.CAknSingleStyleListBox.text"
 	x="13" y="3" width="-4" height="16" />

<rectangle key="listitem.CAknSinglePopupMenuStyleListBox.text"
 	x="8" y="2" width="-4" height="16" />
 	
<rectangle key="listitem.CAknSingleGraphicStyleListBox.text"
 	x="26" y="3" width="-4" height="16" />
<rectangle key="listitem.CAknSingleGraphicStyleListBox.image"
 	x="2" y="3" width="16" height="16" />

<rectangle key="listitem.CAknSingleGraphicPopupMenuStyleListBox.text"
 	x="24" y="2" width="-4" height="16" />
<rectangle key="listitem.CAknSingleGraphicPopupMenuStyleListBox.image"
 	x="2" y="1" width="16" height="16" />

<rectangle key="listitem.CAknSingleGraphicPopupMenuStyleListBoxMulti.text"
 	x="24" y="2" width="-4" height="16" />
 	
<rectangle key="listitem.CAknSingleNumberStyleListBox.number"
 	x="2" y="3" width="17" height="16" />	<!-- was -149 -->
<rectangle key="listitem.CAknSingleNumberStyleListBox.text"
 	x="26" y="3" width="-4" height="12" />

<rectangle key="listitem.CAknSingleHeadingStyleListBox.text"
 	x="52" y="2" width="-4" height="16" />
<rectangle key="listitem.CAknSingleHeadingStyleListBox.headingText"
 	x="4" y="4" width="42" height="12" />	<!-- N.B.: 113 (131?) in doc -->

<rectangle key="listitem.CAknSingleHeadingPopupMenuStyleListBox.text"
 	x="52" y="2" width="-4" height="16" />
<rectangle key="listitem.CAknSingleHeadingPopupMenuStyleListBox.headingText"
 	x="4" y="4" width="42" height="12" />	<!-- N.B.: 113 (131?) in doc -->

<rectangle key="listitem.CAknSingleGraphicHeadingStyleListBox.text"
 	x="52" y="2" width="-4" height="16" />
<rectangle key="listitem.CAknSingleGraphicHeadingStyleListBox.headingText"
 	x="20" y="4" width="26" height="12" />	<!-- N.B.: 113 (131?) -->
<rectangle key="listitem.CAknSingleGraphicHeadingStyleListBox.image"
 	x="2" y="2" width="16" height="16" />
 
 <rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBox.text"
 	x="52" y="2" width="-4" height="16" />
<rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBox.headingText"
 	x="20" y="4" width="26" height="12" />	<!-- N.B.: 113 (131?) -->
<rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBox.image"
 	x="2" y="2" width="16" height="16" />

 <rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBoxMulti.text"
 	x="52" y="2" width="-4" height="16" />
<rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBoxMulti.headingText"
 	x="20" y="4" width="26" height="12" />	<!-- N.B.: 113 (131?) -->
 
<rectangle key="listitem.CAknSingleLargeStyleListBox.text"
 	x="57" y="9" width="-4" height="16" />
<rectangle key="listitem.CAknSingleLargeStyleListBox.image"
 	x="7" y="2" width="42" height="29" />
 
<rectangle key="listitem.CAknSingleNumberHeadingStyleListBox.text"
 	x="57" y="3" width="-4" height="16" />
<rectangle key="listitem.CAknSingleNumberHeadingStyleListBox.headingText"
 	x="18" y="5" width="33" height="12" />		<!-- N.B. 118 -->
<rectangle key="listitem.CAknSingleNumberHeadingStyleListBox.number"
 	x="2" y="5" width="14" height="12" />
 
<rectangle key="listitem.CAknDoubleStyleListBox.text"
 	x="13" y="5" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleStyleListBox.secondaryText"
 	x="18" y="24" width="-4" height="12" />

<rectangle key="listitem.CAknDoublePopupMenuStyleListBox.text"
 	x="8" y="6" width="-4" height="16" />
<rectangle key="listitem.CAknDoublePopupMenuStyleListBox.secondaryText"
 	x="14" y="25" width="-4" height="12" />

<rectangle key="listitem.CAknDoubleStyle2ListBox.text"
 	x="13" y="4" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleStyle2ListBox.secondaryText"
 	x="13" y="22" width="-4" height="16" />

<rectangle key="listitem.CAknDouble2PopupMenuStyleListBox.text"
 	x="8" y="6" width="-4" height="16" />
<rectangle key="listitem.CAknDouble2PopupMenuStyleListBox.secondaryText"
 	x="8" y="24" width="-4" height="16" />

<rectangle key="listitem.CAknDoubleNumberStyleListBox.number"
 	x="2" y="5" width="19" height="12" /> <!-- was 149 -->
<rectangle key="listitem.CAknDoubleNumberStyleListBox.text"
 	x="26" y="5" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleNumberStyleListBox.secondaryText"
 	x="31" y="24" width="-4" height="12" />

<rectangle key="listitem.CAknDoubleTimeStyleListBox.text"
 	x="57" y="5" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleTimeStyleListBox.secondaryText"
 	x="62" y="24" width="-4" height="12" />
<rectangle key="listitem.CAknDoubleTimeStyleListBox.time1Text"
 	x="2" y="5" width="49" height="16" /> <!-- n.b.: was 118 (122?) -->
<rectangle key="listitem.CAknDoubleTimeStyleListBox.time2Text"
 	x="2" y="24" width="49" height="12" /> <!-- n.b.: was 118 (122?) -->

<rectangle key="listitem.CAknDoubleLargeStyleListBox.text"
 	x="57" y="4" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleLargeStyleListBox.secondaryText"
 	x="62" y="22" width="-4" height="16" />	<!-- n.b.: was 57 -->
<rectangle key="listitem.CAknDoubleLargeStyleListBox.image"
 	x="7" y="4" width="42" height="36" />

<!-- not sure what this is
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.text"
 	x="22" y="6" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.secondaryText"
 	x="28" y="25" width="-4" height="16" />	
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.image"
 	x="2" y="6" width="16" height="16" />
-->

<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.text"
 	x="57" y="4" width="-4" height="16" />
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.secondaryText"
 	x="62" y="22" width="-4" height="16" />	<!-- n.b.: was 57 -->
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.image"
 	x="7" y="4" width="42" height="36" />

<rectangle key="listbox.searchfield.bounds.popup"
	x="3" y="0" width="-1" height="31" />
<rectangle key="listbox.searchfield.bounds.search"
	x="0" y="0" width="0" height="28" />
<rectangle key="listbox.searchfield.icon"
	x="2" y="0" width="24" height="26" />
<rectangle key="listbox.searchfield.input"
	x="19" y="2" width="-2" height="-2" />
		
