<color key="screen.background" r="255" g="255" b="255"/>
<color key="status.bar.color" r="12" g="110" b="213"/>
<color key="control.pane.text" r="0" g="0" b="0"/>
<color key="navi.pane.text" r="255" g="255" b="255"/>
<color key="navi.tab.face" r="255" g="255" b="255"/>
<color key="navi.tab.text" r="0" g="0" b="0"/>
<color key="navi.tab.shade" r="0" g="73" b="148"/>
<color key="navi.tab.back" r="74" g="146" b="222"/>
<color key="navi.tab.backText" r="57" g="85" b="255"/>
<color key="navi.tab.arrow" r="255" g="255" b="255"/>
<color key="navi.volume.shade" r="0" g="73" b="148"/>
<color key="listitem.text" r="0" g="0" b="0"/>

<boolean key="is.scalable.ui" value="true" />
<boolean key="draw.msk" value="false" />

<color key="EEikColorWindowBackground" r="255" g="255" b="255"/>
<color key="EEikColorWindowText" r="0" g="0" b="0"/>
<color key="EEikColorControlBackground" r="255" g="255" b="255"/>
<color key="EEikColorControlText" r="0" g="0" b="0"/>
<color key="EEikColorControlSurroundBackground" r="100" g="100" b="100"/>
<color key="EEikColorControlSurroundText" r="0" g="0" b="0"/>
<color key="EEikColorControlHighlightBackground" r="200" g="200" b="200"/>
<color key="EEikColorControlHighlightText" r="0" g="0" b="0"/>
<color key="EEikColorControlDimmedBackground" r="200" g="200" b="200"/>
<color key="EEikColorControlDimmedText" r="100" g="100" b="100"/>
<color key="EEikColorControlDimmedHighlightBackground" r="200" g="200" b="200"/>
<color key="EEikColorControlDimmedHighlightText" r="100" g="100" b="100"/>
<color key="EEikColorDialogBackground" r="255" g="255" b="255"/>
<color key="EEikColorDialogText" r="0" g="0" b="0"/>
<color key="EEikColorDialogTitle" r="200" g="200" b="200"/>
<color key="EEikColorDialogTitlePressed" r="200" g="200" b="200"/>
<color key="EEikColorDialogTitleText" r="0" g="0" b="0"/>
<color key="EEikColorDialogTitleTextPressed" r="0" g="0" b="0"/>
<color key="EEikColorMenubarBackground" r="255" g="255" b="255"/>
<color key="EEikColorMenubarText" r="0" g="0" b="0"/>
<color key="EEikColorMenubarTitleBackground" r="255" g="255" b="255"/>
<color key="EEikColorMenubarTitleText" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneBackground" r="255" g="255" b="255"/>
<color key="EEikColorMenuPaneText" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneHighlight" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneTextHighlight" r="255" g="255" b="255"/>
<color key="EEikColorMenuPaneDimmedHighlight" r="255" g="255" b="255"/>
<color key="EEikColorMenuPaneDimmedText" r="0" g="0" b="0"/>
<color key="EEikColorMenuPaneDimmedTextHighlight" r="0" g="0" b="0"/>
<color key="EEikColorButtonFaceClear" r="255" g="255" b="255"/>
<color key="EEikColorButtonFaceSet" r="255" g="255" b="255"/>
<color key="EEikColorButtonFaceSetPressed" r="255" g="255" b="255"/>
<color key="EEikColorButtonFaceClearPressed" r="255" g="255" b="255"/>
<color key="EEikColorButtonText" r="0" g="0" b="0"/>
<color key="EEikColorButtonTextPressed" r="0" g="0" b="0"/>
<color key="EEikColorButtonTextDimmed" r="0" g="0" b="0"/>
<color key="EEikColorMsgWinForeground" r="0" g="0" b="0"/>
<color key="EEikColorMsgWinBackground" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarBorder" r="100" g="100" b="100"/>
<color key="EEikColorScrollBarShaft" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarShaftDimmed" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarShaftPressed" r="255" g="255" b="255"/>
<color key="EEikColorScrollBarNoShaftOrThumb" r="255" g="255" b="25"/>
<color key="EEikColorScrollButtonIcon" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonIconPressed" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonIconDimmed" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonThumbBackground" r="255" g="255" b="255"/>
<color key="EEikColorScrollButtonThumbBackgroundPressed" r="255" g="255" b="255"/>
<color key="EEikColorScrollThumbDimmed" r="255" g="255" b="25"/>
<color key="EEikColorScrollThumbEdge" r="255" g="255" b="255"/>
<color key="EEikColorToolbarBackground" r="255" g="255" b="255"/>
<color key="EEikColorToolbarText" r="0" g="0" b="0"/>
<color key="EEikColorStatusPaneText" r="0" g="0" b="0"/>
<color key="EEikColorLabelText" r="0" g="0" b="0"/>
<color key="EEikColorLabelTextEmphasis" r="0" g="0" b="0"/>
<color key="EEikColorLabelDimmedText" r="0" g="0" b="0"/>
<color key="EEikColorLabelHighlightPartialEmphasis" r="255" g="255" b="255"/>
<color key="EEikColorLabelHighlightFullEmphasis" r="255" g="255" b="255"/>

<color key="EEikColorLabelBackgroundPartialEmphasis" r="85" g="85" b="85"/>
<color key="EEikColorLabelBackgroundFullEmphasis" r="0" g="0" b="0"/>

<colorAlias key="EEikColorStatusPaneBackground" ref="screen.background"/>

<!-- all of these are found relative to the string key "image.dir" -->
<maskedImage key="context.default.icon" imageFile="default_context.bmp" maskFile="default_context_mask.bmp"/>
<maskedImage key="context.missing.icon" imageFile="missing_context.bmp" maskFile="missing_context_mask.bmp"/>
<maskedImage key="slider.image" imageFile="slider_edit.bmp" maskFile="slider_edit_mask.bmp"/>
<maskedImage key="slider.settingslist.image" imageFile="slider_settings_edit.bmp" maskFile="slider_settings_edit_mask.bmp"/>

<maskedImage key="note.CAknErrorNote.icon" imageFile="qgn_note_error.bmp" maskFile="qgn_note_error_mask_soft.bmp"/>
<maskedImage key="note.CAknInformationNote.icon" imageFile="qgn_note_info.bmp" maskFile="qgn_note_info_mask_soft.bmp"/>
<maskedImage key="note.CAknConfirmationNote.icon" imageFile="qgn_note_ok.bmp" maskFile="qgn_note_ok_mask_soft.bmp"/>
<maskedImage key="note.CAknWarningNote.icon" imageFile="qgn_note_warning.bmp" maskFile="qgn_note_warning_mask_soft.bmp"/>
<maskedImage key="note.progress.icon" imageFile="qgn_note_progress.bmp" maskFile="qgn_note_progress_mask_soft.bmp"/>
<maskedImage key="note.query.icon" imageFile="qgn_note_query.bmp" maskFile="qgn_note_query_mask_soft.bmp"/>

<maskedImage key="note.EAknGlobalInformationNote.icon" imageFile="qgn_note_info.bmp" maskFile="qgn_note_info_mask_soft.bmp"/>
<maskedImage key="note.EAknGlobalWarningNote.icon" imageFile="qgn_note_warning.bmp" maskFile="qgn_note_warning_mask_soft.bmp"/>
<maskedImage key="note.EAknGlobalConfirmationNote.icon" imageFile="qgn_note_ok.bmp" maskFile="qgn_note_ok_mask_soft.bmp"/>
<maskedImage key="note.EAknGlobalErrorNote.icon" imageFile="qgn_note_error.bmp" maskFile="qgn_note_error_mask_soft.bmp"/>

<maskedImage key="listbox.find.icon" imageFile="qgn_indi_find_glass.bmp" maskFile="qgn_indi_find_glass_mask_soft.bmp"/>

<maskedImage key="note.progress.bar" imageFile="qgn_graf_bar_wait_1.bmp" maskFile="qgn_graf_bar_wait_1_mask_soft.bmp"/>

<maskedImage key="volume_speaker_indicator" imageFile="qgn_indi_speaker.bmp" maskFile="qgn_indi_speaker_mask_soft.bmp"/> 
<maskedImage key="volume_earpiece_indicator" imageFile="qgn_indi_earpiece.bmp" maskFile="qgn_indi_earpiece_mask_soft.bmp"/> 
<maskedImage key="volume_mic_indicator" imageFile="qgn_indi_mic.bmp" maskFile="qgn_indi_mic_mask_soft.bmp"/> 

<maskedImage key="popup.selector.icon" imageFile="popup_selector.bmp" maskFile="popup_selector_mask.bmp"/>
<maskedImage key="popup.selector.icon.small" imageFile="popup_selector_small.bmp" maskFile="popup_selector_mask_small.bmp"/>

<maskedImage key="msk.context.options.icon" imageFile="msk_context_options.bmp" maskFile="msk_context_options_mask.bmp"/>
<maskedImage key="msk.left.key.icon" imageFile="msk_left_key.bmp" maskFile="msk_left_key_mask.bmp"/>


<integer key="control.pane.text.margin" value="5"/>
<integer key="slider.rowspacing" value="8"/>
<integer key="extra.padding" value="0"/>
<integer key="form.single.extra.padding" value="0"/>
<integer key="form.double.extra.padding" value="0"/>

<boolean key="status.bar.gradient" value="true"/>

<color key="CEikEdwin.ColorControlText" r="32" g="144" b="32"/>

<color key="CAknSettingItemList.CompulsoryIndicator" r="255" g="101" b="156" />
<color key="CAknSettingItemList.ContentBackground" r="57" g="81" b="255" />
<color key="CAknSettingItemList.ContentForeground" r="255" g="255" b="255" />

<color key="volume.settingitem.onColor" r="255" g="255" b="255" />
<color key="volume.settingitem.offColor" r="200" g="200" b="200" />

<!-- Shadow colors for drawing shadows around dialogs and menus -->
<color key="control.shadow.inner" r="115" g="117" b="115" />
<color key="control.shadow.outer" r="156" g="154" b="156" />

<color key="control.button.outline" r="175" g="186" b="192" />
<color key="control.button.fill" r="226" g="231" b="233" />
<color key="control.button.shadow.inner" r="122" g="140" b="150" />
<color key="control.button.shadow.outer" r="101" g="119" b="129" />

<integer key="control.button.text.margin" value="10"/>


