<dimension key="navi.indicator.size" width="16" height="30"/>

<dimension key="context.icon.size" width="88" height="88"/>

<integer key="note.padding" value="5" />

<integer key="form.inset" value="40"/>

<dimension key="note.icon.size" width="60" height="80" />
<dimension key="note.inset" width="6" height="2" />
<rectangle key="query.editor" x="15" y="11" width="300" height="46" />

<integer key="form.inset" value="40"/>
<integer key="form.divider.offset.single" value="100"/>
<integer key="form.divider.offset.double" value="12"/>
<integer key="form.padding" value="10"/>
<dimension key="form.image.size" width="32" height="32"/>

<integer key="list.padding" value="12"/>
<maskedImage key="listbox.mark.icon" imageFile="qgn_indi_marked_add.bmp" maskFile="qgn_indi_marked_add_mask_soft.bmp"/>

<integer key="settingitemlist.numbered.padding" value="40"/>
<integer key="settingitemlist.padding.y" value="6"/>
<integer key="settingitemlist.padding.x" value="12"/>
<integer key="settingitemlist.content.x" value="80"/>
<integer key="settingitemlist.indi.padding" value="8"/>
<integer key="settingitemlist.content.height" value="32"/>

<integer key="progress.bar.height" value="20"/>
<integer key="note.progress.offsetFromBottom" value="40"/>

<integer key="tab.corner" value="4"/>

<integer key="naviVolume.bar.width" value="10"/>
<integer key="naviVolume.bar.arcWidth" value="8"/>
<integer key="naviVolume.bar.arcHeight" value="8"/>


<integer key="volume.bar.width" value="12"/>
<integer key="volume.padding.height" value="8"/>

<integer key="list.row.height.single" value="44" />
<integer key="list.row.height.single.large" value="88" />
<integer key="list.row.height.double" value="88" />
<integer key="list.query.row.height.single" value="44" />
<integer key="list.query.row.height.single.large" value="88" />
<integer key="list.query.row.height.double" value="88" />

<integer key="note.text.lineGap" value="10" />

<!-- These dimensions are used in every layout. 

	The pattern is, x and y are absolute.
	If width is negative, the right side is calculated as the RHS of the parent
	plus this negative width.  Same goes for height.  
	Otherwise (non-negative), the width and height are absolute.
-->

<rectangle key="listitem.CAknSingleStyleListBox.text"
 	x="26" y="6" width="-8" height="32" />

<rectangle key="listitem.CAknSinglePopupMenuStyleListBox.text"
 	x="16" y="4" width="-8" height="32" />
 	
<rectangle key="listitem.CAknSingleGraphicStyleListBox.text"
 	x="52" y="6" width="-8" height="32" />
<rectangle key="listitem.CAknSingleGraphicStyleListBox.image"
 	x="4" y="6" width="32" height="32" />

<rectangle key="listitem.CAknSingleGraphicPopupMenuStyleListBox.text"
 	x="48" y="4" width="-8" height="32" />
<rectangle key="listitem.CAknSingleGraphicPopupMenuStyleListBox.image"
 	x="4" y="2" width="32" height="32" />

<rectangle key="listitem.CAknSingleGraphicPopupMenuStyleListBoxMulti.text"
 	x="48" y="4" width="-8" height="32" />
 	
<rectangle key="listitem.CAknSingleNumberStyleListBox.number"
 	x="4" y="6" width="34" height="32" />
<rectangle key="listitem.CAknSingleNumberStyleListBox.text"
 	x="52" y="6" width="-8" height="24" />

<rectangle key="listitem.CAknSingleHeadingStyleListBox.text"
 	x="104" y="4" width="-8" height="32" />
<rectangle key="listitem.CAknSingleHeadingStyleListBox.headingText"
 	x="8" y="8" width="84" height="24" />

<rectangle key="listitem.CAknSingleHeadingPopupMenuStyleListBox.text"
 	x="104" y="4" width="-8" height="32" />
<rectangle key="listitem.CAknSingleHeadingPopupMenuStyleListBox.headingText"
 	x="8" y="8" width="84" height="24" />

<rectangle key="listitem.CAknSingleGraphicHeadingStyleListBox.text"
 	x="104" y="4" width="-8" height="32" />
<rectangle key="listitem.CAknSingleGraphicHeadingStyleListBox.headingText"
 	x="40" y="8" width="52" height="24" />
<rectangle key="listitem.CAknSingleGraphicHeadingStyleListBox.image"
 	x="4" y="4" width="32" height="32" />
 
 <rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBox.text"
 	x="104" y="4" width="-8" height="32" />
<rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBox.headingText"
 	x="40" y="8" width="52" height="24" />
<rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBox.image"
 	x="4" y="4" width="32" height="32" />

 <rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBoxMulti.text"
 	x="104" y="4" width="-8" height="32" />
<rectangle key="listitem.CAknSingleGraphicHeadingPopupMenuStyleListBoxMulti.headingText"
 	x="40" y="8" width="52" height="24" />
 
<rectangle key="listitem.CAknSingleLargeStyleListBox.text"
 	x="114" y="18" width="-8" height="32" />
<rectangle key="listitem.CAknSingleLargeStyleListBox.image"
 	x="14" y="4" width="84" height="58" />
 
<rectangle key="listitem.CAknSingleNumberHeadingStyleListBox.text"
 	x="114" y="6" width="-8" height="32" />
<rectangle key="listitem.CAknSingleNumberHeadingStyleListBox.headingText"
 	x="36" y="10" width="66" height="24" />
<rectangle key="listitem.CAknSingleNumberHeadingStyleListBox.number"
 	x="4" y="10" width="28" height="24" />
 
<rectangle key="listitem.CAknDoubleStyleListBox.text"
 	x="26" y="10" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleStyleListBox.secondaryText"
 	x="36" y="48" width="-8" height="24" />

<rectangle key="listitem.CAknDoublePopupMenuStyleListBox.text"
 	x="16" y="12" width="-8" height="32" />
<rectangle key="listitem.CAknDoublePopupMenuStyleListBox.secondaryText"
 	x="28" y="50" width="-8" height="24" />

<rectangle key="listitem.CAknDoubleStyle2ListBox.text"
 	x="26" y="8" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleStyle2ListBox.secondaryText"
 	x="26" y="44" width="-8" height="32" />

<rectangle key="listitem.CAknDouble2PopupMenuStyleListBox.text"
 	x="16" y="12" width="-8" height="32" />
<rectangle key="listitem.CAknDouble2PopupMenuStyleListBox.secondaryText"
 	x="16" y="48" width="-8" height="32" />

<rectangle key="listitem.CAknDoubleNumberStyleListBox.number"
 	x="4" y="10" width="38" height="24" />
<rectangle key="listitem.CAknDoubleNumberStyleListBox.text"
 	x="52" y="10" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleNumberStyleListBox.secondaryText"
 	x="62" y="48" width="-8" height="24" />

<rectangle key="listitem.CAknDoubleTimeStyleListBox.text"
 	x="114" y="10" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleTimeStyleListBox.secondaryText"
 	x="124" y="48" width="-8" height="24" />
<rectangle key="listitem.CAknDoubleTimeStyleListBox.time1Text"
 	x="4" y="10" width="98" height="32" />
<rectangle key="listitem.CAknDoubleTimeStyleListBox.time2Text"
 	x="4" y="48" width="98" height="24" />

<rectangle key="listitem.CAknDoubleLargeStyleListBox.text"
 	x="114" y="8" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleLargeStyleListBox.secondaryText"
 	x="124" y="44" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleLargeStyleListBox.image"
 	x="14" y="8" width="84" height="72" />

<!-- not sure what this is
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.text"
 	x="44" y="12" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.secondaryText"
 	x="56" y="50" width="-8" height="32" />	
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.image"
 	x="4" y="12" width="32" height="32" />
-->

<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.text"
 	x="114" y="8" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.secondaryText"
 	x="124" y="44" width="-8" height="32" />
<rectangle key="listitem.CAknDoubleLargeGraphicPopupMenuStyleListBox.image"
 	x="14" y="8" width="84" height="72" />

<rectangle key="listbox.searchfield.bounds.popup"
	x="6" y="0" width="-2" height="62" />
<rectangle key="listbox.searchfield.bounds.search"
	x="0" y="0" width="0" height="56" />
<rectangle key="listbox.searchfield.icon"
	x="4" y="0" width="48" height="52" />
<rectangle key="listbox.searchfield.input"
	x="38" y="4" width="-4" height="-4" />
		
