<color key="status.bar.gradient.start" r="16" g="80" b="160"/>
<color key="status.bar.gradient.end" r="16" g="80" b="216"/>
<color key="status.title.color" r="255" g="255" b="255"/>
<colorAlias key="control.pane.background"  ref="status.bar.gradient.end"/>
<colorAlias key="control.pane.gradient.start" ref="status.bar.gradient.end"/>
<colorAlias key="control.pane.gradient.end" ref="status.bar.gradient.end"/>

<integer key="status.bar.count" value="2"/>		
<integer key="list.query.maxRows.single" value="5" />
<integer key="list.query.maxRows.double" value="2" />

<boolean key="is.portrait" value="false"/>
<boolean key="is.landscape" value="true"/>
<boolean key="show.context.icon" value="false"/>
<boolean key="cba.align.center" value="false"/>

<integer key="naviVolume.bar.space" value="2"/>

