<color key="status.bar.gradient.start" r="16" g="80" b="160"/>
<color key="status.bar.gradient.end" r="16" g="80" b="216"/>
<color key="status.title.color" r="0" g="0" b="0"/>
<colorAlias key="control.pane.background" ref="screen.background"/>

<position key="context.icon.position" x="0" y="0"/>

<integer key="control.pane.text.margin" value="1"/>
<integer key="list.query.maxRows.single" value="5" />
<integer key="list.query.maxRows.double" value="3" />

<integer key="status.bar.count" value="1"/>

<boolean key="is.portrait" value="true"/>
<boolean key="is.landscape" value="false"/>
<boolean key="show.context.icon" value="true"/>

<integer key="naviVolume.bar.space" value="1"/>