<dimension key="navi.indicator.size" width="12" height="23"/>

<dimension key="context.icon.size" width="54" height="54"/>

<integer key="form.inset" value="30"/>
<integer key="form.divider.offset.single" value="75"/>
<integer key="form.divider.offset.double" value="9"/>
<integer key="form.padding" value="8"/>
<dimension key="form.image.size" width="24" height="24"/>

<dimension key="note.icon.size" width="40" height="60" />
<dimension key="note.inset" width="4" height="1" />
<integer key="note.padding" value="4" />
<rectangle key="query.editor" x="11" y="8" width="200" height="34" />

<integer key="list.padding" value="6"/>
<maskedImage key="listbox.mark.icon" imageFile="qgn_indi_marked_add.bmp" maskFile="qgn_indi_marked_add_mask_soft.bmp"/>

<integer key="settingitemlist.numbered.padding" value="30"/>
<integer key="settingitemlist.padding" value="12"/>

<integer key="tab.corner" value="3"/>

<integer key="settingitemlist.numbered.padding" value="30"/>
<integer key="settingitemlist.padding.y" value="4"/>
<integer key="settingitemlist.padding.x" value="8"/>
<integer key="settingitemlist.indi.padding" value="6"/>
<integer key="settingitemlist.titlepadding" value="6"/>

<integer key="naviVolume.bar.width" value="7"/>
<integer key="naviVolume.bar.arcWidth" value="5"/>
<integer key="naviVolume.bar.arcHeight" value="5"/>

<integer key="volume.bar.width" value="8"/>
<integer key="volume.padding.height" value="6"/>

<integer key="note.text.lineGap" value="6" />

