<color key="navi.tab.face" r="244" g="244" b="244"/>
<color key="navi.tab.text" r="81" g="98" b="118"/>
<color key="navi.tab.shade" r="200" g="200" b="200"/>
<color key="navi.tab.back" r="165" g="186" b="206"/>
<color key="navi.tab.backText" r="255" g="255" b="255"/>
<color key="navi.tab.arrow" r="81" g="98" b="118"/>
<color key="navi.pane.text" r="105" g="129" b="155"/>
<color key="status.title.color" r="103" g="127" b="154"/>
<color key="control.pane.text" r="84" g="97" b="128"/>
<color key="listitem.text" r="84" g="97" b="128"/>

<boolean key="decorations" value="false"/>	
<boolean key="show.context.icon" value="false"/>

<color key="status.bar.gradient.start" r="222" g="231" b="231"/>
<color key="status.bar.gradient.end" r="222" g="231" b="231"/>
<color key="status.bar.color" r="222" g="231" b="231"/>
<color key="CAknSettingItemList.ContentBackground" r="132" g="166" b="206" />

<dimension key="navi.indicator.size" width="18" height="35"/>

<dimension key="context.icon.size" width="78" height="78"/>

<integer key="form.inset" value="45"/>
<integer key="form.divider.offset.single" value="107"/>
<integer key="form.divider.offset.double" value="18"/>
<integer key="form.padding" value="12"/>
<dimension key="form.image.size" width="36" height="36"/>

<dimension key="note.icon.size" width="60" height="90" />
<dimension key="note.inset" width="4" height="2" />
<integer key="note.padding" value="5" />
<rectangle key="query.editor" x="16" y="12" width="420" height="45" />

<integer key="list.padding" value="14"/>
<maskedImage key="listbox.mark.icon" imageFile="qgn_indi_marked_add.bmp" maskFile="qgn_indi_marked_add_mask_soft.bmp"/>

<integer key="settingitemlist.numbered.padding" value="45"/>
<integer key="settingitemlist.padding" value="18"/>

<integer key="tab.corner" value="4"/>

<integer key="settingitemlist.numbered.padding" value="45"/>
<integer key="settingitemlist.padding.y" value="6"/>
<integer key="settingitemlist.padding.x" value="12"/>
<integer key="settingitemlist.indi.padding" value="9"/>
<integer key="settingitemlist.titlepadding" value="9"/>

<integer key="naviVolume.bar.width" value="11"/>
<integer key="naviVolume.bar.arcWidth" value="8"/>
<integer key="naviVolume.bar.arcHeight" value="8"/>

<integer key="volume.bar.width" value="12"/>
<integer key="volume.padding.height" value="9"/>

<integer key="extra.padding" value="-1"/>
<integer key="form.single.extra.padding" value="-3"/>
<integer key="form.double.extra.padding" value="0"/>

<integer key="note.text.lineGap" value="9" />
