/*
* Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/
package com.nokia.sdt.emf.dm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * Stores information about generated files.
 * @model
 */
public interface IGeneratedFiles extends EObject {
	/**
	 * Get the list of files generated by this model. This is a
	 * list of project relative paths, as obtain from Eclipse IPath.
	 * @model type="java.lang.String"
	 */
	EList getFiles();

}
