<event name="handleKeyEvent" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}KeyEventL"
    descriptionKey="handleKeyEventDescription"
/>
<event name="foregroundEvent" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}ForegroundEventL"
    descriptionKey="foregroundEventDescription"
/>
<event name="switchOnEvent" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}SwitchOnEventL"
    descriptionKey="switchOnEventDescription"
/>
<event name="systemEvent" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}SystemEventL"
    descriptionKey="systemEventDescription"
/>
<event name="applicationSpecificEvent" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}ApplicationSpecificEventL"
    descriptionKey="applicationSpecificEventDescription"
/>
<event name="handleStatusPaneSizeChanged" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}StatusPaneSizeChanged"
    descriptionKey="handleStatusPaneSizeChangedDescription"
/>
<event name="viewEvent" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}ViewEventL"
    descriptionKey="viewEventDescription"
/>
<event name="handleCommand" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}CommandL"
    descriptionKey="handleCommandDescription"
/>
<event name="initializeMenuPane" category="Menu" 
    handlerNameTemplate="Handle{title(name)}DynInitMenuPaneL"
    descriptionKey="initializeMenuPaneDescription"
/>
<event name="offerKeyToApp" category="Menu" 
    handlerNameTemplate="Handle{title(name)}OfferKeyToAppL"
    descriptionKey="offerKeyToAppDescription"
/>
<event name="handleResourceChanged" category="AppUi" 
    handlerNameTemplate="Handle{title(name)}ResourceChangedL"
    descriptionKey="handleResourceChangedDescription"
/>
