/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/
package com.nokia.carbide.remoteconnections.discovery.pccs.pccsnative;

import com.sun.jna.Structure;

/**
 *  This file was originally autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 *  but modified to work with Carbide.
 */
public class UP_PERSONALITY extends Structure {
	/// Size of the structure
	public int dwSize;
	/// Personality code
	public byte bPersonalityCode;
	/// Index of String Descriptor describing Personality Code
	public byte bPersonalityIndex;
	public UP_PERSONALITY() {
		super();
	}
	/**
	 * @param dwSize Size of the structure<br>
	 * @param bPersonalityCode Personality code<br>
	 * @param bPersonalityIndex Index of String Descriptor describing Personality Code
	 */
	public UP_PERSONALITY(int dwSize, byte bPersonalityCode, byte bPersonalityIndex) {
		super();
		this.dwSize = dwSize;
		this.bPersonalityCode = bPersonalityCode;
		this.bPersonalityIndex = bPersonalityIndex;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected UP_PERSONALITY newInstance() { return new UP_PERSONALITY(); }
	public static UP_PERSONALITY[] newArray(int arrayLength) {
		return null;
//		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(UP_PERSONALITY.class, arrayLength);
	}
	public static class ByReference extends UP_PERSONALITY implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends UP_PERSONALITY implements com.sun.jna.Structure.ByValue {}

}
