/*
* Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/
package com.nokia.carbide.remoteconnections.discovery.pccs.pccsnative;

import com.sun.jna.Structure;
import com.sun.jna.ptr.ShortByReference;

/**
 *  This file was originally autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 *  but modified to work with Carbide.
 */
public class UP_STRING_DESCRIPTOR extends Structure {
	/// Size of the structure
	public int dwSize;
	/// String descriptor type
	public byte bDescriptorType;
	/**
	 * Descriptor text<br>
	 * C type : WCHAR*
	 */
	public ShortByReference pstrDescription;
	public UP_STRING_DESCRIPTOR() {
		super();
	}
	/**
	 * @param dwSize Size of the structure<br>
	 * @param bDescriptorType String descriptor type<br>
	 * @param pstrDescription Descriptor text<br>
	 * C type : WCHAR*
	 */
	public UP_STRING_DESCRIPTOR(int dwSize, byte bDescriptorType, ShortByReference pstrDescription) {
		super();
		this.dwSize = dwSize;
		this.bDescriptorType = bDescriptorType;
		this.pstrDescription = pstrDescription;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected UP_STRING_DESCRIPTOR newInstance() { return new UP_STRING_DESCRIPTOR(); }
	public static UP_STRING_DESCRIPTOR[] newArray(int arrayLength) {
		return null;
//		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(UP_STRING_DESCRIPTOR.class, arrayLength);
	}
	public static class ByReference extends UP_STRING_DESCRIPTOR implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends UP_STRING_DESCRIPTOR implements com.sun.jna.Structure.ByValue {}

}
